/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author admin pc
 */
public class data_bahan extends javax.swing.JFrame {

    /**
     * Creates new form data_bahan
     */
    public data_bahan() {
        initComponents();
          setLocationRelativeTo(null);
    }
    public JTextField getid_bahan() {
        return id_bahan1;
    }
    public JTextField getnama_bahan() {
        return nama_bahan1;
    }
    public JTextField getwarna_bahan() {
        return warna_bahan1;
    }
    public JTextField getstok() {
        return stok1;
    }
    public JTextField getharga() {
        return harga1;
    }
    public JButton getsave() {
        return save;
    }
    public JButton getcancel() {
        return cancel;
    }
    public JButton gettambah() {
        return tambah;
    }
    public JButton gethapus() {
        return hapus;
    }
    public JButton getedit() {
        return edit;
    }
    public JTable gettabel(){
        return tabel_bahan;
    }
    public JButton getkembali(){
        return kembali_data_bahan;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        data_bahan = new javax.swing.JLabel();
        warna_bahan = new javax.swing.JLabel();
        warna_bahan1 = new javax.swing.JTextField();
        cancel = new javax.swing.JButton();
        save = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel_bahan = new javax.swing.JTable();
        tambah = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        fauzia_collection = new javax.swing.JLabel();
        id_bahan = new javax.swing.JLabel();
        id_bahan1 = new javax.swing.JTextField();
        kembali_data_bahan = new javax.swing.JButton();
        nama_bahan = new javax.swing.JLabel();
        nama_bahan1 = new javax.swing.JTextField();
        stok = new javax.swing.JLabel();
        stok1 = new javax.swing.JTextField();
        harga = new javax.swing.JLabel();
        harga1 = new javax.swing.JTextField();
        background_data_bahan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        data_bahan.setFont(new java.awt.Font("Poor Richard", 0, 24)); // NOI18N
        data_bahan.setText("DATA BAHAN");
        getContentPane().add(data_bahan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        warna_bahan.setFont(new java.awt.Font("Poor Richard", 0, 24)); // NOI18N
        warna_bahan.setText("Warna Bahan      :");
        getContentPane().add(warna_bahan, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, -1, -1));
        getContentPane().add(warna_bahan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 120, 170, 30));

        cancel.setFont(new java.awt.Font("Poor Richard", 0, 24)); // NOI18N
        cancel.setText("Batal");
        getContentPane().add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 460, 110, -1));

        save.setFont(new java.awt.Font("Poor Richard", 0, 24)); // NOI18N
        save.setText("Simpan");
        getContentPane().add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, 110, -1));

        tabel_bahan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabel_bahan);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 730, 160));

        tambah.setFont(new java.awt.Font("Poor Richard", 0, 24)); // NOI18N
        tambah.setText("Tambah");
        getContentPane().add(tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 460, 110, -1));

        hapus.setFont(new java.awt.Font("Poor Richard", 0, 24)); // NOI18N
        hapus.setText("Hapus");
        getContentPane().add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 460, 110, -1));

        edit.setFont(new java.awt.Font("Poor Richard", 0, 24)); // NOI18N
        edit.setText("Ubah");
        getContentPane().add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 460, 110, -1));

        fauzia_collection.setFont(new java.awt.Font("Poor Richard", 2, 24)); // NOI18N
        fauzia_collection.setText("Fauzia Collection");
        getContentPane().add(fauzia_collection, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 580, 170, -1));

        id_bahan.setFont(new java.awt.Font("Poor Richard", 0, 24)); // NOI18N
        id_bahan.setText("Id Bahan                 :");
        getContentPane().add(id_bahan, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));
        getContentPane().add(id_bahan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 170, 30));

        kembali_data_bahan.setFont(new java.awt.Font("Poor Richard", 0, 12)); // NOI18N
        kembali_data_bahan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/back-button.png"))); // NOI18N
        getContentPane().add(kembali_data_bahan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, 50, 50));

        nama_bahan.setFont(new java.awt.Font("Poor Richard", 0, 24)); // NOI18N
        nama_bahan.setText("Nama Bahan        :");
        getContentPane().add(nama_bahan, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));
        getContentPane().add(nama_bahan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 170, 30));

        stok.setFont(new java.awt.Font("Poor Richard", 0, 24)); // NOI18N
        stok.setText("Stok                            :");
        getContentPane().add(stok, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, -1, -1));
        getContentPane().add(stok1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 170, 170, 30));

        harga.setFont(new java.awt.Font("Poor Richard", 0, 24)); // NOI18N
        harga.setText("Harga                       :");
        getContentPane().add(harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));
        getContentPane().add(harga1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 170, 30));

        background_data_bahan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Yellow Background.png"))); // NOI18N
        getContentPane().add(background_data_bahan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(data_bahan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(data_bahan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(data_bahan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(data_bahan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new data_bahan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background_data_bahan;
    private javax.swing.JButton cancel;
    private javax.swing.JLabel data_bahan;
    private javax.swing.JButton edit;
    private javax.swing.JLabel fauzia_collection;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel harga;
    private javax.swing.JTextField harga1;
    private javax.swing.JLabel id_bahan;
    private javax.swing.JTextField id_bahan1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton kembali_data_bahan;
    private javax.swing.JLabel nama_bahan;
    private javax.swing.JTextField nama_bahan1;
    private javax.swing.JButton save;
    private javax.swing.JLabel stok;
    private javax.swing.JTextField stok1;
    private javax.swing.JTable tabel_bahan;
    private javax.swing.JButton tambah;
    private javax.swing.JLabel warna_bahan;
    private javax.swing.JTextField warna_bahan1;
    // End of variables declaration//GEN-END:variables
}
