/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.JTextField;
/**
 *
 * @author admin pc
 */
public class data_customer extends javax.swing.JFrame {

    /**
     * Creates new form data_customer
     */
    public data_customer() {
        initComponents();
          setLocationRelativeTo(null);
    }
    public JTextField getnama_customer() {
        return nama_customer1;
    }
    public JTextField getid_customer() {
        return id_customer1;
    }
    public JTextField getalamat_customer() {
        return alamat_customer1;
    }
    public JTextField getnoHp() {
        return no_hp1;
    }
    public JButton getsave() {
        return save;
    }
    public JButton getcancel() {
        return cancel;
    }
    public JButton gettambah() {
        return tambah;
    }
    public JButton gethapus() {
        return hapus;
    }
    public JButton getedit() {
        return edit;
    }
    public JTable gettabel(){
        return tabel_customer;
    }
    public JButton getkembali(){
        return kembali_data_customer;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fauzia_collection = new javax.swing.JLabel();
        data_customer = new javax.swing.JLabel();
        no_hp = new javax.swing.JLabel();
        nama_customer = new javax.swing.JLabel();
        alamat_customer = new javax.swing.JLabel();
        no_hp1 = new javax.swing.JTextField();
        nama_customer1 = new javax.swing.JTextField();
        alamat_customer1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_customer = new javax.swing.JTable();
        save = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        tambah = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        id_customer = new javax.swing.JLabel();
        id_customer1 = new javax.swing.JTextField();
        kembali_data_customer = new javax.swing.JButton();
        background_data_customer = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fauzia_collection.setFont(new java.awt.Font("Poor Richard", 2, 24)); // NOI18N
        fauzia_collection.setText("Fauzia Collection");
        getContentPane().add(fauzia_collection, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 580, 190, -1));

        data_customer.setFont(new java.awt.Font("Poor Richard", 0, 24)); // NOI18N
        data_customer.setText("DATA CUSTOMER");
        getContentPane().add(data_customer, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        no_hp.setFont(new java.awt.Font("Poor Richard", 0, 24)); // NOI18N
        no_hp.setText("No HandPhone :");
        getContentPane().add(no_hp, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        nama_customer.setFont(new java.awt.Font("Poor Richard", 0, 24)); // NOI18N
        nama_customer.setText("Nama                     :");
        getContentPane().add(nama_customer, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        alamat_customer.setFont(new java.awt.Font("Poor Richard", 0, 24)); // NOI18N
        alamat_customer.setText("Alamat                  :");
        getContentPane().add(alamat_customer, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));
        getContentPane().add(no_hp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 170, 30));
        getContentPane().add(nama_customer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 170, 30));
        getContentPane().add(alamat_customer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 170, 30));

        tabel_customer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabel_customer);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, 400, 270));

        save.setFont(new java.awt.Font("Poor Richard", 0, 24)); // NOI18N
        save.setText("Simpan");
        getContentPane().add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 110, -1));

        edit.setFont(new java.awt.Font("Poor Richard", 0, 24)); // NOI18N
        edit.setText("Ubah");
        getContentPane().add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 440, 110, -1));

        cancel.setFont(new java.awt.Font("Poor Richard", 0, 24)); // NOI18N
        cancel.setText("Batal");
        getContentPane().add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, 110, -1));

        tambah.setFont(new java.awt.Font("Poor Richard", 0, 24)); // NOI18N
        tambah.setText("Tambah");
        getContentPane().add(tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 440, 110, -1));

        hapus.setFont(new java.awt.Font("Poor Richard", 0, 24)); // NOI18N
        hapus.setText("Hapus");
        getContentPane().add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 440, 110, -1));

        id_customer.setFont(new java.awt.Font("Poor Richard", 0, 24)); // NOI18N
        id_customer.setText("Id Customer       :");
        getContentPane().add(id_customer, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));
        getContentPane().add(id_customer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 170, 30));

        kembali_data_customer.setFont(new java.awt.Font("Poor Richard", 0, 12)); // NOI18N
        kembali_data_customer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/back-button.png"))); // NOI18N
        getContentPane().add(kembali_data_customer, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, 50, 50));

        background_data_customer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Yellow Background.png"))); // NOI18N
        getContentPane().add(background_data_customer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(data_customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(data_customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(data_customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(data_customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new data_customer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alamat_customer;
    private javax.swing.JTextField alamat_customer1;
    private javax.swing.JLabel background_data_customer;
    private javax.swing.JButton cancel;
    private javax.swing.JLabel data_customer;
    private javax.swing.JButton edit;
    private javax.swing.JLabel fauzia_collection;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel id_customer;
    private javax.swing.JTextField id_customer1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton kembali_data_customer;
    private javax.swing.JLabel nama_customer;
    private javax.swing.JTextField nama_customer1;
    private javax.swing.JLabel no_hp;
    private javax.swing.JTextField no_hp1;
    private javax.swing.JButton save;
    private javax.swing.JTable tabel_customer;
    private javax.swing.JButton tambah;
    // End of variables declaration//GEN-END:variables

}
