/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JButton;

/**
 *
 * @author admin pc
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
          setLocationRelativeTo(null);
    }
    public String getusername(){
        return user_name1.getText();
    }
    public String getpassword(){
        String pass="";
        char passArray[]=password1.getPassword();
        for (int i = 0; i < passArray.length; i++) {
            pass+=passArray[i];
        }
        return pass;
    }
    public JButton getok(){
        return ok;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fauzia_collection = new javax.swing.JLabel();
        user_name = new javax.swing.JLabel();
        user_name1 = new javax.swing.JTextField();
        password = new javax.swing.JLabel();
        password1 = new javax.swing.JPasswordField();
        ok = new javax.swing.JButton();
        login = new javax.swing.JLabel();
        background_login = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fauzia_collection.setFont(new java.awt.Font("Poor Richard", 2, 24)); // NOI18N
        fauzia_collection.setText("Fauzia Collection");
        getContentPane().add(fauzia_collection, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 580, 170, -1));

        user_name.setFont(new java.awt.Font("Poor Richard", 0, 24)); // NOI18N
        user_name.setText("User Name :");
        getContentPane().add(user_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, -1, -1));
        getContentPane().add(user_name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, 140, 30));

        password.setFont(new java.awt.Font("Poor Richard", 0, 24)); // NOI18N
        password.setText("Password     :");
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, -1, -1));
        getContentPane().add(password1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, 140, 30));

        ok.setFont(new java.awt.Font("Poor Richard", 0, 14)); // NOI18N
        ok.setText("OK");
        getContentPane().add(ok, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 390, 80, 40));

        login.setFont(new java.awt.Font("Poor Richard", 0, 24)); // NOI18N
        login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/user.png"))); // NOI18N
        getContentPane().add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 230, 220));

        background_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Yellow Background.png"))); // NOI18N
        getContentPane().add(background_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background_login;
    private javax.swing.JLabel fauzia_collection;
    private javax.swing.JLabel login;
    private javax.swing.JButton ok;
    private javax.swing.JLabel password;
    private javax.swing.JPasswordField password1;
    private javax.swing.JLabel user_name;
    private javax.swing.JTextField user_name1;
    // End of variables declaration//GEN-END:variables
}
