/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JButton;

/**
 *
 * @author admin pc
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menuf
     */
    public menu() {
        initComponents();
          setLocationRelativeTo(null);
    }
    
    public JButton getdata_customer1() {
        return data_customer;
    }
    public JButton getdata_pesanan1() {
        return data_pesanan;
    }
   
    public JButton getdata_bahan1() {
        return data_bahan;
    }
  
    public JButton getkeluar1() {
        return keluar;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        keluar = new javax.swing.JButton();
        data_bahan = new javax.swing.JButton();
        data_pesanan = new javax.swing.JButton();
        icon_menu = new javax.swing.JLabel();
        data_customer = new javax.swing.JButton();
        fauzia_collection = new javax.swing.JLabel();
        background_menu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        keluar.setFont(new java.awt.Font("Poor Richard", 0, 18)); // NOI18N
        keluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/exitsip.png"))); // NOI18N
        getContentPane().add(keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 470, 170, 110));

        data_bahan.setFont(new java.awt.Font("Poor Richard", 0, 18)); // NOI18N
        data_bahan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/tissue.png"))); // NOI18N
        data_bahan.setText("DATA BAHAN");
        getContentPane().add(data_bahan, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 250, 90));

        data_pesanan.setFont(new java.awt.Font("Poor Richard", 0, 18)); // NOI18N
        data_pesanan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/order.png"))); // NOI18N
        data_pesanan.setText("DATA PESANAN");
        getContentPane().add(data_pesanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 250, 250, 90));

        icon_menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/menu3.png"))); // NOI18N
        getContentPane().add(icon_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, -1, -1));

        data_customer.setFont(new java.awt.Font("Poor Richard", 0, 18)); // NOI18N
        data_customer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/add-user1.png"))); // NOI18N
        data_customer.setText("DATA CUSTOMER");
        getContentPane().add(data_customer, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 250, 90));

        fauzia_collection.setFont(new java.awt.Font("Poor Richard", 2, 24)); // NOI18N
        fauzia_collection.setText("Fauzia Collection");
        getContentPane().add(fauzia_collection, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 580, 170, -1));

        background_menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Yellow Background.png"))); // NOI18N
        getContentPane().add(background_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background_menu;
    private javax.swing.JButton data_bahan;
    private javax.swing.JButton data_customer;
    private javax.swing.JButton data_pesanan;
    private javax.swing.JLabel fauzia_collection;
    private javax.swing.JLabel icon_menu;
    private javax.swing.JButton keluar;
    // End of variables declaration//GEN-END:variables

    
}
